### ISSUE TITLE
CSS rule in admin.css and icons.css too broad

### ISSUE THREAD

**Issue by eliorivero** [Obox/layerswp#108]
These rules in admin.css and icons.css respectively
```css
[class^="icon-"], [class*=" icon-"]{
    font-size: 32px;
}
```
```css
[class^="icon-"], [class*=" icon-"] {
	font-family: 'layers-interface';
    ...
```
are too broad and affect everything that has `icon-` in the class when it should not. To name one example, an icon picker with a class like `icon-picker`. You should apply them only where you really need it, not anywhere and everywhere irrestrictively.
