### ISSUE TITLE
Please add blog grid

### ISSUE THREAD

**Issue by VadymVolos** [Obox/layerswp#282]
Yes, I know that I can create a page and select the blog widget.

But when I point out that this wordpress blog page. Grid Blog is lost, and the posts are displayed as standard in one column. And I want to be able to do the column (grid 2, 3, 4).

**Comment by marcperel** [comment]
We may bring this in with LayersPro thanks @VadymVolos

**Comment by VadymVolos** [comment]
I did! :)
```css
/* blog page grid */
@media only screen and (min-width: 769px) {
    .blog .wrapper-content .type-post {
        width: 31.33333%;
        float: left;
        padding-right: 0%;
        background: #ECECEC;
        margin-right: 2%;
        box-sizing: border-box;
    }
    .blog .sidebar {
        display: none;
    }
    .blog .span-8 {
        width: 102%;
        max-width: 102%;
    }
    .blog .thumbnail {
        height: 175px;
    }
}
/* /blog page grid */
```
