### ISSUE TITLE
Embed video - in post - not responsive

### ISSUE THREAD

**Issue by VadymVolos** [Obox/layerswp#294]
Hi! :)
![112](https://cloud.githubusercontent.com/assets/12669290/11301273/87be46e0-8f9e-11e5-943b-7c4b0b30de84.png)
![113](https://cloud.githubusercontent.com/assets/12669290/11301274/87cc28c8-8f9e-11e5-9b69-512cf68071db.png)
![114](https://cloud.githubusercontent.com/assets/12669290/11301272/879faa8c-8f9e-11e5-9314-b3c2c2e589d3.png)

**Comment by VadymVolos** [comment]
I did (It works, but the error remained.):
```css
.blog .thumbnail.push-bottom iframe {
    display: block;
    overflow: hidden;
    z-index: 1;
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
}
.single .thumbnail.push-bottom iframe {
    height: 100%;
    min-height: 371px;
}
```
